### ISSUE TITLE
Error when getting all cosmetics

### ISSUE THREAD

**Issue by Gentlecat2210** [djlorenzouasset/Athena#18]
[10:05:29 INF] Added "Character_Jumpsuit_Scrap_Mutable" with 1 channels variants.
[10:05:29 INF] Added "MCS_Jumpsuit_Scrap" with 0 channels variants.
[10:05:29 INF] Added "Hero_Jumpsuit_Scrap" with 0 channels variants.
[10:05:29 ERR] Could not read CustomizableObject correctly
CUE4Parse.UE4.Exceptions.ParserException: FName could not be read, requested index 82, name map size 47
FAssetArchive Info: FortniteGame/Plugins/GameFeatures/MeshCosmetics/Content/Jumpsuit/F_MED_Jumpsuit_Scrap/CO/CO_F_MED_Jumpsuit_Scrap.uasset | Pos:3630 Length:55430 (6.5% done)
   at CUE4Parse.UE4.Assets.Exports.CustomizableObject.FCustomizableObjectClothingAssetData..ctor(FAssetArchive Ar)
   at CUE4Parse.UE4.Assets.Exports.CustomizableObject.UCustomizableObject.<>c__DisplayClass5_0.<Deserialize>b__1()
   at CUE4Parse.UE4.Assets.Exports.CustomizableObject.UCustomizableObject.Deserialize(FAssetArchive Ar, Int64 validPos)
   at CUE4Parse.UE4.Assets.AbstractUePackage.DeserializeObject(UObject obj, FAssetArchive Ar, Int64 serialSize)
[10:05:29 INF] Added "CO_F_MED_Jumpsuit_Scrap" with 0 channels variants.
[10:05:29 ERR] Could not read CustomizableObjectResourceDataContainer correctly
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at CUE4Parse.UE4.Assets.Objects.Unversioned.FUnversionedHeader..ctor(FArchive Ar)
   at CUE4Parse.UE4.Assets.Exports.UObject.DeserializePropertiesUnversioned(List`1 properties, FAssetArchive Ar, UStruct struc)
   at CUE4Parse.UE4.Assets.Objects.FInstancedStruct..ctor(FAssetArchive Ar)
   at CUE4Parse.UE4.Assets.Objects.UScriptStruct..ctor(FAssetArchive Ar, String structName, UStruct struc, Nullable`1 type)
   at CUE4Parse.UE4.Assets.Objects.Properties.StructProperty..ctor(FAssetArchive Ar, FPropertyTagData tagData, ReadType type)
   at CUE4Parse.UE4.Assets.Objects.Properties.FPropertyTagType.ReadPropertyTagType(FAssetArchive Ar, String propertyType, FPropertyTagData tagData, ReadType type)
   at CUE4Parse.UE4.Assets.Objects.FPropertyTag..ctor(FAssetArchive Ar, PropertyInfo info, ReadType type)
   at CUE4Parse.UE4.Assets.Exports.UObject.DeserializePropertiesUnversioned(List`1 properties, FAssetArchive Ar, UStruct struc)
   at CUE4Parse.UE4.Assets.Objects.UScriptStruct..ctor(FAssetArchive Ar, String structName, UStruct struc, Nullable`1 type)
   at CUE4Parse.UE4.Assets.Objects.Properties.StructProperty..ctor(FAssetArchive Ar, FPropertyTagData tagData, ReadType type)
   at CUE4Parse.UE4.Assets.Objects.Properties.FPropertyTagType.ReadPropertyTagType(FAssetArchive Ar, String propertyType, FPropertyTagData tagData, ReadType type)
   at CUE4Parse.UE4.Assets.Objects.FPropertyTag..ctor(FAssetArchive Ar, PropertyInfo info, ReadType type)
   at CUE4Parse.UE4.Assets.Exports.UObject.DeserializePropertiesUnversioned(List`1 properties, FAssetArchive Ar, UStruct struc)
   at CUE4Parse.UE4.Assets.Exports.UObject.Deserialize(FAssetArchive Ar, Int64 validPos)
   at CUE4Parse.UE4.Assets.AbstractUePackage.DeserializeObject(UObject obj, FAssetArchive Ar, Int64 serialSize)
[10:05:29 INF] Added "CO_F_MED_Jumpsuit_Scrap_SR_0" with 0 channels variants.
[10:05:29 INF] Added "CP_Athena_Head_F_Jumpsuit_Scrap_Mutable" with 0 channels variants.
[10:05:29 INF] Added "CP_Athena_Body_F_Jumpsuit_Scrap_Mutable" with 0 channels variants.

**Comment by djlorenzouasset** [comment]
update your athena version to latest and try again

**Comment by Gentlecat2210** [comment]
It was on the latest version, 1.6.0

**Comment by djlorenzouasset** [comment]
what mappins are you using?
